name: Destroy Terraform Resources for Workshop3

on:
  workflow_dispatch:

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Initialize Terraform
        working-directory: workshop3
        run: terraform init

      - name: Plan Terraform destruction
        working-directory: workshop3
        run: terraform plan -destroy -out=tfdestroy

      - name: Destroy Terraform resources
        working-directory: workshop3
        run: terraform apply -auto-approve tfdestroy
